### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by thunderer** [thunderer/BattleNetApi#1]
- [ ] change namespace from BlizzardApi to BattleNetApi,
- [ ] implement remaining World of Warcraft endpoints (especially Character variations),
- [ ] make this package ready to be published on Packagist,
- [ ] write about it on Blizzard forums and get some people testing and reporting bugs.

**Comment by LogansUA** [comment]
- Fomat code with [PSR](http://www.php-fig.org/) code style

**Comment by thunderer** [comment]
@LogansUA Do you use this project? It is fairly completed, but I lost interest in it long time ago. Do you need anything or have any bugs to report? Maybe you'd like to contribute something?

**Comment by LogansUA** [comment]
@thunderer no :smile: i was looking for some kind of project, because i also start to write Blizzard API Client, and found this issue

**Comment by thunderer** [comment]
@LogansUA If you'd like to work with me on this project then you're welcome, from what I remember Diablo3 and Starcraft2 should be completed (I've played them so I understand their data), I only struggled with WoW, I didn't play it and don't know if everything is correct and ready.

**Comment by LogansUA** [comment]
@thunderer I'll think about that :smile: I've played in WoW about 8-9 years, so i know almost all data from there.
